---
name: Check for broken links

on:
  pull_request:
    branches:
      - main

jobs:
  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: [".md", ".mdx"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: LinkCheck
        uses: Consensys-Incorporated/github-actions/docs-link-check@89c262a30cae735be99dc776f9556b796fb456ca # v1.0.0
        with:
          FILE_EXTENSION: ${{ matrix.file-extensions }}
